# FriendlyChat Codelab

use_frameworks!
platform :ios, '7.0'

# project 'FriendlyChatSwift', 'Debug - local'=>:debug, 'Debug - staging'=>:debug, 'Debug - PRODUCTION'=>:debug

pod 'Firebase/Storage'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'

target 'FriendlyChatSwift' do
end
